# Generated by Django 4.2 on 2023-05-30 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('dob', models.DateField(default=None)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 30, 18, 55, 25, 591898))),
                ('sex', models.CharField(max_length=30)),
            ],
        ),
    ]
